ERROR	2023-11-03 04:28:15,818	0	org.hyperledger.fabric.gateway.impl.TransactionImpl	[main]	No valid proposal responses received. 2 peer error responses: error in simulation: transaction returned with failure: Asset asset70 does not exist; error in simulation: transaction returned with failure: Asset asset70 does not exist
ERROR	2023-11-03 04:29:26,410	0	org.hyperledger.fabric.gateway.impl.TransactionImpl	[main]	No valid proposal responses received. 2 peer error responses: error in simulation: transaction returned with failure: Asset asset1 already exists; error in simulation: transaction returned with failure: Asset asset1 already exists
ERROR	2023-11-03 07:35:47,375	1	org.hyperledger.fabric.sdk.Channel	[main]	Channel Channel{id: 1, name: mychannel} Sending proposal with transaction: 2497cf51013e542926bbb4b59e6cdf6c7238f5412c663232e4a2c02e12f2c9d1 to Peer{ id: 2, name: peer0.org1.example.com, channelName: mychannel, url: grpcs://localhost:7051, mspid: Org1MSP} failed because of: gRPC failure=Status{code=UNKNOWN, description=error validating proposal: access denied: channel [mychannel] creator org [Org1MSP], cause=null}
java.lang.Exception: io.grpc.StatusRuntimeException: UNKNOWN: error validating proposal: access denied: channel [mychannel] creator org [Org1MSP]
	at org.hyperledger.fabric.sdk.Channel.sendProposalToPeers(Channel.java:4965)
	at org.hyperledger.fabric.sdk.Channel.sendProposalToPeers(Channel.java:4868)
	at org.hyperledger.fabric.sdk.Channel.getConfigBlock(Channel.java:941)
	at org.hyperledger.fabric.sdk.Channel.getConfigBlock(Channel.java:907)
	at org.hyperledger.fabric.sdk.Channel.parseConfigBlock(Channel.java:1994)
	at org.hyperledger.fabric.sdk.Channel.loadCACertificates(Channel.java:1831)
	at org.hyperledger.fabric.sdk.Channel.initialize(Channel.java:1222)
	at org.hyperledger.fabric.gateway.impl.NetworkImpl.initializeChannel(NetworkImpl.java:59)
	at org.hyperledger.fabric.gateway.impl.NetworkImpl.<init>(NetworkImpl.java:50)
	at org.hyperledger.fabric.gateway.impl.GatewayImpl.getNetwork(GatewayImpl.java:252)
	at application.java.App.main(App.java:53)
Caused by: io.grpc.StatusRuntimeException: UNKNOWN: error validating proposal: access denied: channel [mychannel] creator org [Org1MSP]
	at io.grpc.Status.asRuntimeException(Status.java:533)
	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:490)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:700)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:399)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:510)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:66)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:630)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$700(ClientCallImpl.java:518)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:692)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:681)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
ERROR	2023-11-03 07:35:47,378	4	org.hyperledger.fabric.sdk.Channel	[main]	getConfigBlock for channel mychannel failed with peer peer0.org1.example.com.  Status FAILURE, details: Channel Channel{id: 1, name: mychannel} Sending proposal with transaction: 2497cf51013e542926bbb4b59e6cdf6c7238f5412c663232e4a2c02e12f2c9d1 to Peer{ id: 2, name: peer0.org1.example.com, channelName: mychannel, url: grpcs://localhost:7051, mspid: Org1MSP} failed because of: gRPC failure=Status{code=UNKNOWN, description=error validating proposal: access denied: channel [mychannel] creator org [Org1MSP], cause=null}
org.hyperledger.fabric.sdk.exception.ProposalException: getConfigBlock for channel mychannel failed with peer peer0.org1.example.com.  Status FAILURE, details: Channel Channel{id: 1, name: mychannel} Sending proposal with transaction: 2497cf51013e542926bbb4b59e6cdf6c7238f5412c663232e4a2c02e12f2c9d1 to Peer{ id: 2, name: peer0.org1.example.com, channelName: mychannel, url: grpcs://localhost:7051, mspid: Org1MSP} failed because of: gRPC failure=Status{code=UNKNOWN, description=error validating proposal: access denied: channel [mychannel] creator org [Org1MSP], cause=null}
	at org.hyperledger.fabric.sdk.Channel.getConfigBlock(Channel.java:952)
	at org.hyperledger.fabric.sdk.Channel.getConfigBlock(Channel.java:907)
	at org.hyperledger.fabric.sdk.Channel.parseConfigBlock(Channel.java:1994)
	at org.hyperledger.fabric.sdk.Channel.loadCACertificates(Channel.java:1831)
	at org.hyperledger.fabric.sdk.Channel.initialize(Channel.java:1222)
	at org.hyperledger.fabric.gateway.impl.NetworkImpl.initializeChannel(NetworkImpl.java:59)
	at org.hyperledger.fabric.gateway.impl.NetworkImpl.<init>(NetworkImpl.java:50)
	at org.hyperledger.fabric.gateway.impl.GatewayImpl.getNetwork(GatewayImpl.java:252)
	at application.java.App.main(App.java:53)
ERROR	2023-11-03 07:35:47,683	309	org.hyperledger.fabric.sdk.ServiceDiscovery	[main]	Error access denied
ERROR	2023-11-03 07:38:41,772	0	org.hyperledger.fabric.gateway.impl.TransactionImpl	[main]	No valid proposal responses received. 2 peer error responses: error in simulation: transaction returned with failure: Asset asset70 does not exist; error in simulation: transaction returned with failure: Asset asset70 does not exist
ERROR	2023-11-03 07:39:15,985	0	org.hyperledger.fabric_ca.sdk.HFCAClient	[main]	POST request to https://localhost:7054 failed request body {"id":"appUser","type":"client","affiliation":"org1.department1","attrs":[]}. Response: {"result":"","errors":[{"code":74,"message":"Identity 'appUser' is already registered"}
],"messages":[],"success":false}
ERROR	2023-11-03 07:39:15,985	0	org.hyperledger.fabric_ca.sdk.HFCAClient	[main]	application.java.RegisterUser$1@18518ccf
ERROR	2023-11-03 12:15:19,441	0	org.hyperledger.fabric.gateway.impl.TransactionImpl	[main]	No valid proposal responses received. 2 peer error responses: error in simulation: transaction returned with failure: Asset asset70 does not exist; error in simulation: transaction returned with failure: Asset asset70 does not exist
ERROR	2023-11-04 14:43:54,687	0	org.hyperledger.fabric_ca.sdk.HFCAClient	[main]	POST request to https://localhost:7054 failed request body {"id":"appUser","type":"client","affiliation":"org1.department1","attrs":[]}. Response: {"result":"","errors":[{"code":74,"message":"Identity 'appUser' is already registered"}
],"messages":[],"success":false}
ERROR	2023-11-04 14:43:54,688	1	org.hyperledger.fabric_ca.sdk.HFCAClient	[main]	application.java.RegisterUser$1@18518ccf
ERROR	2023-11-04 14:47:27,599	0	org.hyperledger.fabric.gateway.impl.TransactionImpl	[main]	No valid proposal responses received. 2 peer error responses: error in simulation: transaction returned with failure: Asset asset70 does not exist; error in simulation: transaction returned with failure: Asset asset70 does not exist
